"""
Renewals page — broker-facing view of policies expiring soon, with
per-row email-draft and mark-contacted actions.

Layout:
- KPI bar: Needs attention now / In 60-day window / Premium at risk /
  Contacted this week.
- One expander per urgency bucket: ⚪ Overdue, 🔴 Urgent (0–14d),
  🟡 Warning (15–30d), 🔵 Watch (31–60d).
- Each expander holds a sortable, row-selectable st.dataframe. When a
  row is selected, an action panel renders below the table with:
    - "Preview Reminder Email" → opens an @st.dialog with the draft
      generated by `draft_renewal_email()`. Inside the dialog the
      broker can edit To/Subject/Body, download the result as .txt,
      or log it as an 'email_draft' contact.
    - "Log contact (skip email)" expander → method + notes + Log
      button. Writes a NotificationLog row via NotificationService.

Data comes from `PolicyService.get_renewal_buckets()` (bucket placement)
and `NotificationService` (contact log + "Contacted this week" KPI).
No SQL lives in this file.
"""
from __future__ import annotations

from datetime import date, datetime, timedelta
from typing import Iterable, Optional

import pandas as pd
import streamlit as st

from core.database import Policy, get_session
from core.notification_service import NotificationService
from core.services import PolicyService
from modules.notifications import draft_renewal_email


# TODO: move to a settings field once the Settings dialog gains a Renewals
# section. For now the agency name is a constant so the email signoff line
# isn't blank.
_AGENCY_NAME = "Truckers National"


# ---------------------------------------------------------------------------
# Small helpers (kept local — pure functions used only by this view).
# ---------------------------------------------------------------------------


def _parse_premium(value) -> float:
    """Best-effort float coercion for the 'premium at risk' KPI.

    Returns 0.0 for anything we can't parse so a malformed value
    doesn't poison the sum across many policies."""
    if value is None:
        return 0.0
    if isinstance(value, (int, float)):
        return float(value)
    try:
        cleaned = str(value).replace("$", "").replace(",", "").strip()
        return float(cleaned) if cleaned else 0.0
    except (ValueError, TypeError):
        return 0.0


def _premium_at_risk(policies: Iterable[Policy]) -> float:
    return sum(_parse_premium(p.premium) for p in policies)


def _policies_to_dataframe(
    policies: list[Policy], notif_service: NotificationService
) -> pd.DataFrame:
    """Display shape: one row per policy with the columns brokers care
    about, plus a 'Last contacted' column populated from NotificationLog."""
    today = date.today()
    rows = []
    for p in policies:
        days_left = (
            (p.expiration_date - today).days if p.expiration_date else None
        )
        last = notif_service.last_contact(p.id)
        rows.append(
            {
                "Customer": p.insured_name or "(no name)",
                "Carrier": p.carrier_name or "—",
                "Policy #": p.policy_number or "—",
                "Type": p.policy_type or "—",
                "Premium": p.premium or "—",
                "Expires": p.expiration_date,
                "Days left": days_left,
                "Last contacted": last.contacted_at if last else None,
            }
        )
    return pd.DataFrame(rows)


def _render_bucket(
    policies: list[Policy],
    title: str,
    hint: str,
    *,
    key: str,
    notif_service: NotificationService,
    expanded: bool = True,
) -> Optional[Policy]:
    """One expander section for a bucket. Returns the selected Policy
    (or None) so the caller can render the action panel right below."""
    if not policies:
        return None
    label = f"{title} — {len(policies)} {'policy' if len(policies) == 1 else 'policies'}"
    with st.expander(label, expanded=expanded):
        st.caption(hint)
        df = _policies_to_dataframe(policies, notif_service)
        grid = st.dataframe(
            df,
            width="stretch",
            hide_index=True,
            selection_mode="single-row",
            on_select="rerun",
            key=f"renewals_table_{key}",
            column_config={
                "Expires": st.column_config.DateColumn(format="MMM DD, YYYY"),
                "Days left": st.column_config.NumberColumn(format="%d"),
                "Last contacted": st.column_config.DatetimeColumn(
                    format="MMM DD, YYYY",
                    help="Most recent NotificationLog row for this policy.",
                ),
            },
        )
        rows = getattr(getattr(grid, "selection", None), "rows", []) or []
        if rows:
            selected = policies[rows[0]]
            _render_action_panel(selected, notif_service, key_prefix=key)
            return selected
        return None


def _render_action_panel(
    policy: Policy,
    notif_service: NotificationService,
    *,
    key_prefix: str,
) -> None:
    """Action card shown below the bucket dataframe when a row is selected.

    `key_prefix` plus policy.id guarantees unique widget keys when the same
    policy could conceivably appear in two buckets (it can't, but be
    defensive)."""
    st.markdown(
        f"##### Selected: **{policy.insured_name or '(no name)'}** "
        f"— {policy.policy_number or '(no policy #)'}"
    )

    last = notif_service.last_contact(policy.id)
    if last:
        last_str = last.contacted_at.strftime("%b %d, %Y")
        suffix = f" — _{last.notes}_" if last.notes else ""
        st.caption(f"📞 Last contacted {last_str} via **{last.method}**{suffix}")
    else:
        st.caption("📞 No prior contact logged for this policy.")

    action_col, log_col = st.columns([1, 1])

    if action_col.button(
        "📧 Preview Reminder Email",
        key=f"preview_{key_prefix}_{policy.id}",
        width="stretch",
        type="primary",
    ):
        _renewal_email_dialog(policy.id)

    with log_col.expander("Log contact (skip email)", expanded=False):
        method = st.selectbox(
            "Method",
            ["phone", "manual", "other"],
            key=f"method_{key_prefix}_{policy.id}",
        )
        notes = st.text_area(
            "Notes",
            key=f"notes_{key_prefix}_{policy.id}",
            placeholder="e.g. 'Left voicemail, will retry Thursday'",
            height=80,
        )
        if st.button(
            "Log contact",
            key=f"log_{key_prefix}_{policy.id}",
            type="primary",
            width="stretch",
        ):
            session = get_session(st.session_state.db_engine)
            try:
                NotificationService(session).record_contact(
                    policy_id=policy.id,
                    customer_id=getattr(policy, "customer_id", None),
                    method=method,
                    notes=notes or None,
                )
                session.commit()
                st.toast(
                    f"Logged {method} contact for {policy.policy_number}",
                    icon="✅",
                )
                st.rerun()
            finally:
                session.close()


# ---------------------------------------------------------------------------
# Email-draft dialog — module-level so @st.dialog decoration applies once.
# ---------------------------------------------------------------------------


@st.dialog("📧 Renewal Reminder Draft", width="large")
def _renewal_email_dialog(policy_id: int) -> None:
    """Modal: edit, download, or log a reminder draft for one policy."""
    session = get_session(st.session_state.db_engine)
    try:
        policy = session.get(Policy, policy_id)
        if policy is None:
            st.error("Policy not found — was it deleted in another tab?")
            return

        draft = draft_renewal_email(policy, agency_name=_AGENCY_NAME)

        st.caption(
            "Draft generated from the extracted policy data. Edit any field "
            "before copying. Nothing is sent automatically; this is a "
            "starting point for the broker."
        )

        edited_to = st.text_input(
            "To",
            value=draft.to,
            placeholder="recipient@example.com",
            help="Empty when the insured's email was not extracted. Fill it "
            "in or copy the body and paste into your mail client.",
        )
        edited_subject = st.text_input("Subject", value=draft.subject)
        edited_body = st.text_area("Body", value=draft.body, height=320)

        st.divider()
        dl_col, log_col = st.columns(2)
        dl_col.download_button(
            "⬇️ Download .txt",
            data=edited_body,
            file_name=draft.download_filename,
            mime="text/plain",
            width="stretch",
        )
        if log_col.button(
            "✅ Log as 'email_draft' contact",
            type="primary",
            width="stretch",
        ):
            # Build a notes line that captures who/what was drafted so the
            # log entry is useful even without the email body itself.
            recipient_note = edited_to or "(no recipient on file)"
            NotificationService(session).record_contact(
                policy_id=policy.id,
                customer_id=getattr(policy, "customer_id", None),
                method="email_draft",
                notes=f"Drafted reminder. To: {recipient_note}",
            )
            session.commit()
            st.toast("Logged as 'email_draft' contact", icon="✅")
            st.rerun()
    finally:
        session.close()


# ---------------------------------------------------------------------------
# Page entry point.
# ---------------------------------------------------------------------------


def page_renewals() -> None:
    st.title("🔔 Renewals")
    st.caption(
        "Policies expiring soon, grouped by urgency. Click a row in any "
        "bucket to preview a reminder email or log a contact."
    )

    session = get_session(st.session_state.db_engine)
    try:
        policy_service = PolicyService(session)
        notif_service = NotificationService(session)

        buckets = policy_service.get_renewal_buckets()
        overdue = buckets["overdue"]
        urgent = buckets["urgent"]
        warning = buckets["warning"]
        watch = buckets["watch"]

        total_in_window = len(overdue) + len(urgent) + len(warning) + len(watch)
        attention_now = len(overdue) + len(urgent)
        premium_at_risk = _premium_at_risk(overdue + urgent)

        week_ago = datetime.utcnow() - timedelta(days=7)
        contacted_this_week = notif_service.count_in_window(week_ago, datetime.utcnow())

        k1, k2, k3, k4 = st.columns(4)
        k1.metric(
            "Needs attention now",
            attention_now,
            help="Overdue policies plus those expiring in the next 14 days.",
        )
        k2.metric(
            "In 60-day window",
            total_in_window,
            help="All policies grouped on this page.",
        )
        k3.metric(
            "Premium at risk",
            f"${premium_at_risk:,.0f}",
            help="Sum of premium across overdue + urgent policies. "
            "Non-numeric premium values are skipped.",
        )
        k4.metric(
            "Contacted this week",
            contacted_this_week,
            help="Renewal-related notification log rows in the last 7 days.",
        )

        st.divider()

        if total_in_window == 0:
            st.success(
                "✅ No policies expiring in the next 60 days. Check back in a "
                "few weeks — or extract a new policy from **Process Policies**."
            )
            return

        _render_bucket(
            overdue,
            "⚪ Overdue",
            "These policies have already expired. If a backdated renewal "
            "is still possible, prioritize these first.",
            key="overdue",
            notif_service=notif_service,
        )
        _render_bucket(
            urgent,
            "🔴 Urgent (0–14 days)",
            "Contact these customers today. After 14 days a policy is "
            "uncomfortably close to expiring without coverage.",
            key="urgent",
            notif_service=notif_service,
        )
        _render_bucket(
            warning,
            "🟡 Warning (15–30 days)",
            "Plan outreach over the next week or two.",
            key="warning",
            notif_service=notif_service,
            expanded=False,
        )
        _render_bucket(
            watch,
            "🔵 Watch (31–60 days)",
            "On your radar. Worth a heads-up email but not yet urgent.",
            key="watch",
            notif_service=notif_service,
            expanded=False,
        )
    finally:
        session.close()
