"""Baseline Batch

Revision ID: f6f188f8df82
Revises: 
Create Date: 2026-01-28 17:48:21.731279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f188f8df82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_history', schema=None) as batch_op:
        batch_op.alter_column('policy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'UPDATE'"))
        batch_op.alter_column('policy_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('changes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_policy_history_id'), ['id'], unique=False)
        batch_op.drop_column('previous_data_snapshot')
        batch_op.drop_column('change_description')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_description', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('previous_data_snapshot', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_policy_history_id'))
        batch_op.alter_column('changes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('policy_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('event_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'UPDATE'"))
        batch_op.alter_column('policy_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
